# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: zinc

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo résumé theme powered by Hugo Blox Builder.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "right"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    #    highlight_active_link: true
    logo:
      text: "Yanomic"
      filename: "icon.png"

# Site footer
footer:
  copyright:
    notice: '© {year} Yanomic.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 02, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/HugoBlox/hugo-blox-builder/'
    content_dir: starters/blog/content
    branch: main
